#!/bin/sh

# We want our users to have a simple API to run the Assembler, no matter the language
# it was written in. So, we need a "wrapper" that will hide all language-specific details to do so,
# thus enabling our users to simply type 'Assembler <path>' in order to use it.
# The purpose of this file is to run your project, and the only two lines
# it should contain are '#!/bin/sh' (which means that this file is a script) 
# and the command you use to run your project.
# This file assumes that the main is contained in Main.py 
# "$*" is a variable that holds all the arguments this file has received. So, if you
# run "Assembler-python trout mask replica", $* will hold "trout mask replica".
# Obviously, your project may be more complicated and require a different run file.
# For example, if you're using python version 3, the command should be "python3" instead of "python".
# For this file (Assembler-python) to run when you call "Assembler", rename it to "Assembler".

python Main.py $*